//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostSpectator.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhostSpectator.Translation.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t change the knob of SCP-914..
        /// </summary>
        public static string change914KnobDenied {
            get {
                return ResourceManager.GetString("change914KnobDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t contain SCPs..
        /// </summary>
        public static string containDenied {
            get {
                return ResourceManager.GetString("containDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t open doors..
        /// </summary>
        public static string doorDenied {
            get {
                return ResourceManager.GetString("doorDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting through the elevator..
        /// </summary>
        public static string elevatorTeleport {
            get {
                return ResourceManager.GetString("elevatorTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t interact with generators..
        /// </summary>
        public static string generatorDenied {
            get {
                return ResourceManager.GetString("generatorDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t use the intercom..
        /// </summary>
        public static string intercomDenied {
            get {
                return ResourceManager.GetString("intercomDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t open lockers..
        /// </summary>
        public static string lockerDenied {
            get {
                return ResourceManager.GetString("lockerDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players found..
        /// </summary>
        public static string teleportNone {
            get {
                return ResourceManager.GetString("teleportNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now spectating {0}..
        /// </summary>
        public static string teleportTo {
            get {
                return ResourceManager.GetString("teleportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectators can&apos;t use SCP-914..
        /// </summary>
        public static string use914Denied {
            get {
                return ResourceManager.GetString("use914Denied", resourceCulture);
            }
        }
    }
}
